services:
    bprs_analytics:
        class:  Bprs\AnalyticsBundle\Model\AnalyticsService
        arguments: [ "@doctrine.orm.entity_manager", "@event_dispatcher" ]

    bprs_analytics_listener:
        class:  Bprs\AnalyticsBundle\Event\AnalyticsListener
        arguments: [ "@logger", "@bprs_analytics"]
        tags:
            - { name: kernel.event_listener, event: bprs_analytics.create, method: analyticsCreate }
