bprs_asset:
    class:              "AppBundle\\Entity\\Asset"
    filesystem_map:     "oneup_flysystem.mount_manager"
    worker_queue:       "%env(bprs_asset_worker_queue)%"
    thumb_filesystem:   "%env(thumb_filesystem)%"
    404:                "%env(bprs_asset_404)%"
    adapters:
        posterframe:
            url: '%env(posterframe_url)%'
            path: '%env(posterframe_path)%'
        video:
            url: '%env(video_url)%'
            path: '%env(video_path)%'
            remote: true
        gallery:
            url: '%env(gallery_url)%'
            path: '%env(gallery_path)%'
        cache:
            url: '%env(cache_url)%'
            path: '%env(cache_path)%'
        promo:
            url: '%env(promo_url)%'
            path: '%env(promo_path)%'
        sprite:
            url: 'https://s3.eu-central-1.amazonaws.com/flux2-okto-tv/sprites'
            path: 'https://s3.eu-central-1.amazonaws.com/flux2-okto-tv/sprites'
            remote: true
