jms_serializer:
    metadata:
        auto_detection: false
    visitors:
        json:
            options: JSON_HEX_QUOT

    object_constructors:
            doctrine:
                fallback_strategy: "fallback"
