oktolab_media:
    encoding_filesystem:    "cache"
    worker_queue:           "flux2"
    sprite_worker_queue:    "flux2_sprite"
    episode_class:          "AppBundle\\Entity\\Episode"
    series_class:           "AppBundle\\Entity\\Series"
    asset_class:            "AppBundle\\Entity\\Asset"
    keep_original:          false
    serializing_schema:     "okto"
    resolutions:
        360p:
            name: 360p
            sortNumber: 0
            video_width: 640
            video_height: 360
            adapter: video
            video_bitrate: 3000000
            crf_rate: 23
            preset: slower
            video_framerate: '25'
            audio_bitrate: 128000
        720p:
            name: 720p
            sortNumber: 1
            video_width: 1280
            video_height: 720
            adapter: video
            video_bitrate: 5000000
            crf_rate: 23
            preset: slower
        1080p:
            name: 1080p
            sortNumber: 2
            video_width: 1920
            video_height: 1080
            adapter: video
            video_bitrate: 8000000
            crf_rate: 22
            preset: slower
        UHD:
            name: UHD
            sortNumber: 3
            video_width: 3840
            video_height: 2160
            adapter: video
            video_bitrate: 15000000
            crf_rate: 23
            preset: slower
        SD:
            stereomode: 1
            name: SD
            sortNumber: 0
            video_width: 1920
            video_height: 960
            adapter: video
            video_bitrate: 7500000
            crf_rate: 23
            video_framerate: '25'
            preset: medium
        HD:
            stereomode: 1
            name: HD
            sortNumber: 1
            video_width: 3840
            video_height: 1920
            adapter: video
            video_bitrate: 8000000
            crf_rate: 23
            video_framerate: '25'
            preset: medium

    player_url: "https://content.jwplatform.com/libraries/FJWVLOxx.js" # add me to .env and .env.dist
    origin:
        margin: 2
        position: top-left
        logo: bundles/app/images/player/logo.svg
        url: 'https://www.okto.tv'
