security:

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_BPRS_APPLINK_BACKEND
            - ROLE_BPRS_COMMANDLINE_BACKEND
            - ROLE_BPRS_USER_BACKEND
            - ROLE_BPRS_ASSET_READ
            - ROLE_BPRS_ASSET_DELETE
        ROLE_USER:
            - ROLE_OKTOLAB_PRODUCER
            - ROLE_OKTOLAB_MEDIA_READ
            - ROLE_PR_USER
        ROLE_PR_USER:
            - ROLE_BPRS_ASSET_READ
            - ROLE_BPRS_ASSET_WRITE
            - ROLE_OKTOLAB_USER
        ROLE_OKTOLAB_PRODUCER:
            - ROLE_BPRS_ASSET_WRITE
            - ROLE_OKTOLAB_USER

# ROLE_ADMIN:            TZE BOSSA
# ROLE_USER:             Okto Ppl
# ROLE_PR_USER:          Ppl like Sabin Kargl who snoop around more than they should.
# ROLE_OKTOLAB_PRODUCER: Okto Serie Ppl
# ROLE_OKTOLAB_USER:     Registered User

    providers:
        bprs_applink:
            entity:
                class: BprsAppLinkBundle:Keychain
                property: user

        database:
            entity:
                class: AppBundle:User

    encoders:
        Bprs\AppLinkBundle\Entity\Keychain: plaintext
        Bprs\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        api:
            pattern:  /api
            http_basic: ~
            provider: bprs_applink
            stateless: true
            anonymous: ~

        main:
            pattern:    /
            http_basic: ~
            form_login:
                login_path: bprs_user_login
                check_path: bprs_user_login_check
                #default_target_path: homepage users get redirected to whereever they decided to login
                csrf_token_generator: security.csrf.token_manager #form.csrf_provider
            logout:
                path: bprs_user_logout
                target: homepage
            anonymous: ~
            provider: database
            remember_me:
                secret: '%kernel.secret%'
                httponly: false
                secure: false
            logout_on_user_change: true
            switch_user: { role: ROLE_ADMIN }

    access_control:
        - { path: /backend, roles: ROLE_USER }
        - { path: /backend/admin, roles: ROLE_ADMIN}
