imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        cookie_lifetime: 86400 #1 day
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        name:         "OKTO"
        version:      "Alpha"
        junksize:     "%bprs_asset.junksize%"
        intake_url:   "http://intake.okto.tv"
        oktothek_default_newsletter: "%mailchimp_default_newsletter%"
        oktothek_academy_newsletter: "%mailchimp_academy_newsletter%"
        oktothek_academy_mail:       "%oktothek_academy_mail%"
        okto_streamurl: "%okto_stream_url%"
    charset:    "UTF-8"
    form_themes:
        - 'BprsStyleBundle:Form:fields.html.twig'
    # form:
    #     resources:
    #         - 'BprsStyleBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        resolve_target_entities:
            Bprs\AssetBundle\Entity\AssetInterface:         AppBundle\Entity\Asset
            Oktolab\MediaBundle\Entity\EpisodeInterface:    AppBundle\Entity\Episode
            Oktolab\MediaBundle\Entity\PlaylistInterface:   AppBundle\Entity\Playlist
            Oktolab\MediaBundle\Entity\SeriesInterface:     AppBundle\Entity\Series
            Okto\MediaBundle\Entity\TagInterface:           AppBundle\Entity\Tag
            Bprs\UserBundle\Entity\UserInterface:           AppBundle\Entity\User

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    # spool:     { type: memory }
    spool:
        type: file
        path: '%kernel.root_dir%/spool'

bprs_user:
    class: %bprs_user.class%
    register_header: "Registierung auf OKTO abschließen"
    iforgot_header:  "Passwort auf OKTO zurücksetzen"
    mail:
        commandline_host: %bprs_user.host%
        adress:           %bprs_user.mailadress%
        name:             %bprs_user.name%
    permissions:
        - ROLE_ADMIN
        - ROLE_BPRS_USER_BACKEND
        - ROLE_BPRS_APPLINK_BACKEND
        - ROLE_BPRS_COMMANDLINE_BACKEND
        - ROLE_BPRS_ASSET_READ
        - ROLE_BPRS_ASSET_WRITE
        - ROLE_BPRS_ASSET_DELETE
        - ROLE_OKTOLAB_MEDIA_READ
        - ROLE_OKTOLAB_USER
        - ROLE_OKTOLAB_PRODUCER
        - ROLE_USER
    user_defaults:
        - ROLE_OKTOLAB_USER

oktolab_media:
    encoding_filesystem: cache
    worker_queue: %worker_queue%
    episode_class: AppBundle\Entity\Episode
    series_class: AppBundle\Entity\Series
    asset_class: AppBundle\Entity\Asset
    keep_original: false
    serializing_schema: 'okto'
    resolutions:
        360p:
            name: 360p
            sortNumber: 0
            video_width: 640
            video_height: 360
            adapter: "video"
            video_bitrate: 3000000
            crf_rate:   23
            preset:     "veryslow"
        720p:
            name: 720p
            sortNumber: 1
            video_width: 1280
            video_height: 720
            adapter: "video"
            video_bitrate: 5000000
            crf_rate:   23
            preset:     "veryslow"
        1080p:
            name: 1080p
            sortNumber: 2
            video_width: 1920
            video_height: 1080
            adapter: "video"
            video_bitrate: 8000000
            crf_rate:   23
            preset:     "veryslow"
        UHD:
            name: UHD
            sortNumber: 3
            video_width: 3840
            video_height: 2160
            adapter: "video"
            video_bitrate: 15000000
            crf_rate:   23
            preset:     "veryslow"
    player_url: "%player_url%"
    origin:
        margin: 12
        position: "top-left"
        logo: "bundles/app/images/player/logo.png"

okto_media:
    tag_class: "AppBundle\Entity\Tag"
    user_class: %bprs_user.class%

jms_serializer:
    metadata:
        auto_detection: true
    visitors:
        json:
            options: JSON_HEX_QUOT

bprs_command_line:
    php_path: %php_path%
    worker_queue: %worker_queue%
    redis_backend: "%redis_backend%"

bprs_asset:
    class:  AppBundle\Entity\Asset
    filesystem_map: oneup_flysystem.mount_manager
    worker_queue: %worker_queue%
    thumb_filesystem: posterframe
    404:      "%bprs_asset_404%"
    adapters: "%bprs_asset_adapters%"

oneup_flysystem:
    adapters: "%oneup_flysystem_adapters%"
    filesystems:
        posterframe:
            adapter: posterframe
            mount: posterframe
        video:
            adapter: video
            mount: video
        cache:
            adapter: cache
            mount: cache
        gallery:
            adapter: gallery
            mount: gallery
        promo:
            adapter: promo
            mount: promo

oneup_uploader:
    chunks:
        maxage: 86400
        storage:
            directory: %kernel.cache_dir%/uploader/chunks
    mappings:
        cache:
            frontend: blueimp
            storage:
                type: flysystem
                filesystem: oneup_flysystem.cache_filesystem
        posterframe:
            frontend: blueimp
            storage:
                type: flysystem
                filesystem: oneup_flysystem.posterframe_filesystem
        video:
            frontend: blueimp
            storage:
                type: flysystem
                filesystem: oneup_flysystem.video_filesystem
        gallery:
            frontend: blueimp
            storage:
                type: flysystem
                filesystem: oneup_flysystem.gallery_filesystem
        promo:
            frontend: blueimp
            storage:
                type: flysystem
                filesystem: oneup_flysystem.promo_filesystem

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig   # sliding pagination controls template
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig # sort link template

fos_elastica:
    serializer: ~
    clients:
        default: { host: localhost, port: 9200 }
        # logger: true
    indexes:
        app:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            my_analyzer:
                                type: custom
                                tokenizer: standard
                                filter   : [my_ngram]
                            episode_analyzer:
                                type: custom
                                tokenizer: lowercase
                                filter   : [snowball, my_ngram]
                        filter:
                            my_ngram:
                                type: edgeNGram
                                min_gram: 3
                                max_gram: 20
            types:
                episode:
                    serializer:
                        groups: [search]
                    mappings:
                        name:        { boost: 8, analyzer: episode_analyzer }
                        description: { analyzer: episode_analyzer }
                        series_search:      { boost: 3, analyzer: episode_analyzer }
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Episode
                        provider: ~
                        listener: ~
                        finder: ~
                series:
                    serializer:
                        groups: [search]
                    mappings:
                        name:        { boost: 8, analyzer: episode_analyzer }
                        description: { analyzer: episode_analyzer }
                    persistence:
                        driver: orm
                        model:  AppBundle\Entity\Series
                        provider: ~
                        listener: ~
                        finder: ~
                playlist:
                    serializer:
                        groups: [search]
                    persistence:
                        driver: orm
                        model:  AppBundle\Entity\Playlist
                        provider: ~
                        listener: ~
                        finder: ~
                tag:
                    serializer:
                        groups: [okto]
                    mappings:
                        slug: { boost: 8, analyzer: my_analyzer }
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Tag
                        provider: ~
                        listener: ~
                        finder: ~
                coursetype:
                    serializer:
                        groups: [search]
                    mappings:
                        title:  { boost: 8, analyzer: my_analyzer }
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Course\Coursetype
                        provider: ~
                        listener: ~
                        finder: ~

bprs_sofort:
    customer_id:    %customer_id%
    project_id:     %project_id%
    api_id:         %api_id%

bprs_app_link:
    available_apis: [oktolab_media_api, bprs_asset_api]
