bprs_analytics:
    resource: "@BprsAnalyticsBundle/Controller/"
    type:     annotation
    prefix:   /

bprs_sofort:
    resource: "@BprsSOFORTBundle/Controller/"
    type:     annotation
    prefix:   /

bprs_applink:
    resource: .
    type: bprs_applink

start:
    path:      /
    defaults:  { _controller: AppBundle:Default:oktothek, _locale: de }
    requirements:
        _locale:  de|en

series_redirect:
    path:      /{webtitle}
    defaults:  { _controller: AppBundle:Default:seriesRedirect }

shorturl:
    path:      /watch
    defaults:  { _controller: AppBundle:Default:episodeShort }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /{_locale}
    requirements:
        _locale: de|en

oneup_uploader:
    resource: .
    type: uploader

oktolab_media:
    resource: .
    type:     oktolab_media

bprs_user:
    resource: .
    type: bprs_user

bprs_asset:
    resource: .
    type: bprs_asset

bprs_commandline:
    resource: .
    type: bprs_commandline
    prefix: /{_locale}/backend
