app:
    resource: "@AppBundle/Controller/"
    type:     annotation

oneup_uploader:
    resource: .
    type: uploader

oktolab_media:
    resource: "@OktolabMediaBundle/Controller/"
    type:     annotation
    prefix:   /
