homepage:
    path:      /{_locale}
    defaults:  { _controller: AppBundle:Default:index, _locale: de }
    requirements:
        _locale:  de|en

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /{_locale}
    requirements:
        _locale: de|en

oneup_uploader:
    resource: .
    type: uploader

oktolab_media:
    resource: "@OktolabMediaBundle/Controller/"
    type:     annotation
    prefix:   /

bprs_user:
    resource: .
    type: bprs_user
