security:

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_USER:  ROLE_OKTOLAB_ADMIN
        ROLE_OKTOLAB_ADMIN: ROLE_OKTOLAB_BACKEND
        ROLE_OKTOLAB_BACKEND: ROLE_OKTOLAB_PRODUCER
        ROLE_OKTOLAB_PRODUCER: ROLE_OKTOLAB_USER

    providers:
        bprs_applink:
            entity:
                class: BprsAppLinkBundle:Keychain
                property: user

        database:
            entity:
                class: AppBundle:User

    encoders:
        Bprs\AppLinkBundle\Entity\Keychain: plaintext
        Bprs\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        api:
            pattern:  ^/api
            http_basic: ~
            provider: bprs_applink
            stateless: true

        main:
            pattern:    /
            http_basic: ~
            form_login:
                login_path: bprs_user_login
                check_path: bprs_user_login_check
                default_target_path: homepage
                csrf_token_generator: security.csrf.token_manager #form.csrf_provider
                default_target_path: /de
            logout:
                path: bprs_user_logout
                target: /de
            anonymous: ~
            provider: database

    access_control:
        - { path: /backend, roles: ROLE_USER }
        - { path: /backend/admin, roles: ROLE_ADMIN}
