parameters:
    livestream_template:    "Mail/livestream.html.twig"
    new_post_template:      "Mail/new_post.html.twig"
    new_episode_template:   "Mail/new_episode.html.twig"

services:
    oktothek_post_service:
        class: AppBundle\Model\PostService
        arguments: [ "@doctrine.orm.entity_manager", "@bprs.asset_helper"]

    oktothek_playlist_service:
        class:  AppBundle\Model\PlaylistService
        arguments: [ "@doctrine.orm.entity_manager" ]


    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    mediabundle_user:
        class: MediaBundle\Form\UserType
        arguments: [ "@oktothek_user.repository" ]
        tags:
            - { name: form.type, alias: mediabundle_user }

    user_service:
        class: AppBundle\Model\UserService
        arguments: [ "@doctrine.orm.entity_manager"]

    oktothek_notification_service:
        class: AppBundle\Model\NotificationService
        arguments: [ "@doctrine.orm.entity_manager", "@bprs_user.mailer", "@translator", %livestream_template%, %new_post_template%, %new_episode_template% ]

    oktothek_notification_listener:
        class: AppBundle\Event\NotificationListener
        arguments: [ "@logger", "@oktothek_notification_service" ]
        tags:
            - { name: kernel.event_listener, event: oktolab_media.encoded_episode, method: createNewEpisodeNotifications }

    oktothek_coursepackage:
        class: AppBundle\Model\CoursepackageService
        arguments: [ "@form.factory", "@oktothek_academy" ]

    oktothek_tv:
        class: AppBundle\Model\TvService
        arguments: [ %program_url% ]

    # Asset repository
    oktothek_user.repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments:  [ AppBundle\Entity\User ]

    oktothek_search:
        class: AppBundle\Model\SearchService
        arguments: [ "@fos_elastica.finder.app.episode", "@fos_elastica.finder.app.series", "@fos_elastica.finder.app.playlist", "@fos_elastica.finder.app.tag" ]

    oktothek_academy:
        class: AppBundle\Model\AcademyService
        arguments: [ "@bprs_sofort", "@doctrine.orm.entity_manager", "@router"]

    oktothek_slide:
        class: AppBundle\Model\SliderService
        arguments: [ "@bprs.asset_helper", "@doctrine.orm.entity_manager", "@router"]

# voter
    oktothek_subscription_voter:
        class: AppBundle\Security\SubscriptionVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    oktothek_series_post_voter:
        class:  AppBundle\Security\SeriesPostVoter
        tags:
            - { name: security.voter }
        public: false

# TWIG Extension
    oktothek.twig_extension:
        class: AppBundle\Twig\AcademyExtension
        public: false
        tags:
            - { name: twig.extension }

# Playlist form
    oktothek.episode_repository:
        class: Doctrine\ORM\EntityRepository
        factory:    [ "@doctrine.orm.entity_manager", getRepository ]
        arguments:  [ %oktolab_media.episode_class% ]

    oktothek.playlistitem_type:
        class: AppBundle\Form\PlaylistItemType
        arguments: [ "@oktothek.episode_repository" ]
        tags:
            - { name: form.type, alias: appbundle_playlist_item }
