# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
livestream_template:    "Mail/livestream.html.twig"
new_post_template:      "Mail/new_post.html.twig"
new_episode_template:   "Mail/new_episode.html.twig"

services:
    oktothek_post_service:
        class: AppBundle\Model\PostService
        arguments: [ @doctrine.orm.entity_manager, @bprs.asset_helper]

    oktothek_playlist_service:
        class:  AppBundle\Model\PlaylistService
        arguments: [ @doctrine.orm.entity_manager ]


    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    oktothek_tag.type:
        class: AppBundle\Form\TagType
        arguments: [ @oktothek_tag.repository ]
        tags:
            - { name: form.type, alias: tag }

    user_service:
        class: AppBundle\Model\UserService
        arguments: [ @doctrine.orm.entity_manager]

    oktothek_notification_service:
        class: AppBundle\Model\NotificationService
        arguments: [ @doctrine.orm.entity_manager, @bprs_user.mailer, @translator, %livestream_template%, %new_post_template%, %new_episode_template% ]

    oktothek_notification_listener:
        class: AppBundle\Event\NotificationListener
        arguments: [ @logger, @oktothek_notification_service ]
        tags:
            - { name: kernel.event_listener, event: oktolab_media.encoded_episode, method: createNewEpisodeNotifications }

    # Asset repository
    oktothek_tag.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:  [ "AppBundle\Entity\Tag" ]

    oktothek_search:
        class: AppBundle\Model\SearchService
        arguments: [ @fos_elastica.finder.app.episode, @fos_elastica.finder.app.series, @fos_elastica.finder.app.page, @fos_elastica.finder.app.post ]

    oktothek_academy:
        class: AppBundle\Model\AcademyService
        arguments: [ @bprs_sofort, @doctrine.orm.entity_manager, @router]

# voter
    oktothek_subscription_voter:
        class: AppBundle\Security\SubscriptionVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

# TWIG Extension
    oktothek.twig_extension:
        class: AppBundle\Twig\AcademyExtension
        public: false
        tags:
            - { name: twig.extension }
