<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoursetypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursetypeRepository extends EntityRepository
{
    public function findActiveCoursetypes()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c,i FROM AppBundle:Course\Coursetype c LEFT JOIN c.image i WHERE c.is_active = true')
            ->getResult();
    }
}
