<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoursetypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursetypeRepository extends EntityRepository
{
    public function findActiveCoursetypes($query_only = false)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT ct,c,d,i FROM AppBundle:Course\Coursetype ct
                LEFT JOIN ct.image i
                LEFT JOIN ct.courses c
                LEFT JOIN c.dates d
                WHERE ct.is_active = true
                AND ct.highlight = false
                AND SIZE(ct.courses) != 0
                AND c.max_attendees > SIZE(c.attendees)
                AND c.deadline > :now'
            )->setParameter('now', new \DateTime());

        if ($query_only) {
            return $query;
        }
        return $query->getResult();
    }

    /**
     * returns coursetypes that are:
     * active
     * highlighted
     * courses have free seats
     * courses are in the future
     */
    public function findHighlightedCoursetypes($query_only = false)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT ct,c,d,i FROM AppBundle:Course\Coursetype ct
                LEFT JOIN ct.image i
                LEFT JOIN ct.courses c
                LEFT JOIN c.dates d
                WHERE ct.is_active = true
                AND ct.highlight = true
                AND SIZE(ct.courses) != 0
                AND SIZE(c.attendees) < c.max_attendees
                AND c.deadline > :now'
            )->setParameter('now', new \DateTime());

        if ($query_only) {
            return $query;
        }

        return $query->getResult();
    }

    public function findActiveCoursetype($coursetype)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT ct,c,d,i FROM AppBundle:Course\Coursetype ct
                LEFT JOIN ct.courses c
                LEFT JOIN c.dates d
                LEFT JOIN ct.image i
                WHERE ct.is_active = true
                AND (
                    ct.slug = :coursetype OR
                    ct.id = :coursetype
                )
                AND SIZE(c.attendees) < c.max_attendees
                AND c.deadline > :now'
            )
            ->setParameter('coursetype', $coursetype)
            ->setParameter('now', new \Datetime());

        return $query->getOneOrNullResult();
    }
}
