<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoursetypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursepackageRepository extends EntityRepository
{
    public function findActiveCoursepackages($query_only = false)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT c,i FROM AppBundle:Course\Coursepackage c
                LEFT JOIN c.image i
                WHERE c.is_active = true
            ');

        if ($query_only) {
            return $query;
        }
        return $query->getResult();
    }
}
