<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    public function findCoursesForCoursetypeQuery($coursetype)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM AppBundle:Course\Course c WHERE c.coursetype = :coursetype')
            ->setParameter('coursetype', $coursetype->getId());
    }
}
