<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends EntityRepository
{
    public function findNewestPlaylists($numberPlaylists = 8, $query_only = false)
    {
        $query = $this->getEntityManager()->createQuery(
                "SELECT p FROM AppBundle:Playlist p
                WHERE SIZE(p.items) != 0
                ORDER BY p.createdAt DESC"
            );

        if ($query_only) {
            return $query;
        }
        return $query->setMaxResults($numberPlaylists)->getResult();
    }

    public function findPlaylistsForSeriesQuery($series, $query_only = false)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM AppBundle:Playlist p
                WHERE p.series = :series
                ORDER BY p.createdAt DESC"
            )
            ->setParameter('series', $series->getId());

        if ($query_only) {
            return $query;
        }
        return $query->getResult();
    }
}
