<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\User;

/**
 * PostCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCommentRepository extends EntityRepository
{
    public function findComments($results = 10, $query_only = false)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT c, u FROM AppBundle:PostComment c LEFT JOIN c.user u ORDER BY c.createdAt DESC');

        if ($query_only) {
            return $query;
        }

        return $query->setMaxResults($results)->getResult();
    }

    public function findCommentsForPost($post, $results = 10, $query_only = false)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT c, u, a FROM AppBundle:PostComment c LEFT JOIN c.user u LEFT JOIN c.children a WHERE c.post = :id AND c.parent IS NULL ORDER BY c.createdAt DESC')
            ->setParameter('id', $post->getId());

        if ($query_only) {
            return $query;
        }

        return $query->setMaxResults($results)->getResult();
    }

    public function findCommentsForUser(User $user, $query_only = false)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:PostComment c
                WHERE c.user = :user
                ORDER BY c.createdAt DESC'
            )->setParameter('user', $user->getId());

        if ($query_only) {
            return $query;
        }

        return $query->getResult();
    }
}
