<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideRepository extends EntityRepository
{
    public function findNewestSlides($numberSlides)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM AppBundle:Slide s JOIN s.asset a WHERE s.onlineAt <= :startdate ORDER BY s.onlineAt DESC'
            )
            ->setParameter('startdate', new \DateTime())
            ->setMaxResults($numberSlides)
            ->getResult();
    }

    public function findNewestSlidesByType($numberSlides, $type)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM AppBundle:Slide s JOIN s.asset a WHERE s.onlineAt <= :startdate AND s.slide_type = :type ORDER BY e.onlineAt ASC'
            )
            ->setParameter('startdate', new \DateTime())
            ->setParameter('type', $type)
            ->setMaxResults($numberSlides)
            ->getResult();
    }

    public function findAllSlidesQuery()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT s FROM AppBundle:Slide s LEFT JOIN s.asset a');
    }

    public function findSlide($slide)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s,a FROM AppBundle:Slide s LEFT JOIN s.asset a WHERE s.id = :id'
            )
            ->setParameter('id', $slide)
            ->getOneOrNullResult();
    }
}
