<?php

namespace AppBundle\Entity\Repository;

use Bprs\UserBundle\Entity\UserRepository as BaseRepository;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
    public function findFavorites($user)
    {
        return $this->findFavoritesQuery($user)->getResult();
    }

    public function findFavoritesQuery($user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT f FROM AppBundle:Episode f JOIN f.users u JOIN f.series s WHERE u.id = :user_id')
            ->setParameter('user_id', $user->getId());
    }

    public function findPlaylists($user)
    {
        return $this->findPlaylistsQuery($user);
    }

    public function findPlaylistsQuery($user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AppBundle:Playlist p JOIN p.user u WHERE u.id = :user_id')
            ->setParameter('user_id', $user->getId());
    }

    public function findAbonnements($user)
    {
        return $this->findChannelsQuery($user)->getResult();
    }

    public function findAbonnementsQuery($user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM AppBundle:Abonnement a WHERE a.user = :user_id')
            ->setParameter('user_id', $user->getId());
    }

    public function findAboUsersWithNotificationForNewEpisodes($series, $withEmail = false)
    {
        return $this->findAboUsersWithNotificationForNewEpisodesQuery($series, $withEmail)->getResult();
    }

    public function findAboUsersWithNotificationForNewEpisodesQuery($series, $withEmail = false)
    {
        if ($withEmail) {
            return $this->getEntityManager()
                ->createQuery('SELECT u FROM AppBundle:User u JOIN u.abonnements a WHERE a.series = :series_id AND a.newEpisode = 1 AND a.send_mails = 1')
                ->setParameter('series_id', $series->getId());
        }
        return $this->getEntityManager()
            ->createQuery('SELECT u FROM AppBundle:User u JOIN u.abonnements a WHERE a.series = :series_id AND a.newEpisode = 1')
            ->setParameter('series_id', $series->getId());
    }

    public function findAboUsersWithNotificationForLivestream($series, $withEmail = false)
    {
        return $this->findAboUsersWithNotificationForLivestreamQuery($series, $withEmail)->getResult();
    }

    public function findAboUsersWithNotificationForLivestreamQuery($series, $withEmail = false)
    {
        if ($withEmail) {
            return $this->getEntityManager()
                ->createQuery('SELECT u FROM AppBundle:User u JOIN u.abonnements a WHERE a.series = :series_id AND a.livestream = 1 AND a.send_mails = 1')
                ->setParameter('series_id', $series->getId());
        }
        return $this->getEntityManager()
            ->createQuery('SELECT u FROM AppBundle:User u JOIN u.abonnements a WHERE a.series = :series_id AND a.livestream = 1')
            ->setParameter('series_id', $series->getId());
    }

    public function findAboUsersWithNotificationNewPost($series, $withEmail = false)
    {
        return $this->findAboUsersWithNotificationNewPostQuery($series, $withEmail)->getResult();
    }

    public function findAboUsersWithNotificationNewPostQuery($series, $withEmail = false)
    {
        if ($withEmail) {
            return $this->getEntityManager()
                ->createQuery('SELECT u FROM AppBundle:User u JOIN u.abonnements a WHERE a.series = :series_id AND a.new_post = 1 AND a.send_mails = 1')
                ->setParameter('series_id', $series->getId());
        }
        return $this->getEntityManager()
            ->createQuery('SELECT u FROM AppBundle:User u JOIN u.abonnements a WHERE a.series = :series_id AND a.new_post = 1')
            ->setParameter('series_id', $series->getId());
    }
}
